### ISSUE TITLE
apt module always returns modified status when update is set to true and no version is specified

### ISSUE THREAD

**Issue by Yethal** [jetporch/jetporch#4]
### Version

<-- paste the version/date info from 'jetp --version' -->
build a7a8ceb5e52e3d324c8aca0ce0ee49434c218f83@main
### Steps to Reproduce

1. Create a playbook with an apt module with update set to true and no version specified
2. Run the playbook against a remote
3. Notice the task reported status modified (which may be correct since the package may have been absent)
4. Rerun the playbook
5. Notice the task reported status modified even though nothing changed

**Comment by mpdehaan** [comment]
Thanks, in the future please include a gist or something that shows the playbook line, from chat I recall you had "update: true" in there so taking notes here myself.

With update: true, I think the code doesn't presently check the remote version versus the actual version before trying the update, so that would need to be added.  Also for my own notes, it needs to probably also be done for the yum/dnf module, as this module was based on that one.

**Comment by mpdehaan** [comment]
I've decided to make a lot of this logic common between package modules, and will take care of this for yum and apt hopefully at the same time, and then we can use this same logic with the new packaging submissions

**Comment by mpdehaan** [comment]
Haven't fixed this just yet, but I just I pushed some code to apt and yum to make them use standard module infrastructure, and have already fixed this for yum.  Leaving this open so I don't forget apt.  Initial googling shows I can get this from apt-cache maybe.

**Comment by mpdehaan** [comment]
should be fixed, went with this to get the remote version

apt-cache show {} | grep Version | cut -f2 --delimiter=':'"

let me know if there are any problems, thank you!

**Comment by bellackn** [comment]
hi @mpdehaan, as mentioned on discord, this bug still occurs with the latest build from `main`. 

```
---
- name: Run basic setup steps for Proxmox
  groups:
    - proxmox

  tasks:

    - !apt
      package: "{{ item }}"
      with:
        items:
          - cifs-utils
      update: true
```

leads to this output *every time* you run it via `jetp ssh --playbook playbook_proxmox_base_setup.yml --inventory inventory -vvv
`: https://gist.github.com/bellackn/784e05c3d1b4fc79fb559f81b0bc9d6a

**Comment by mpdehaan** [comment]
The build above looks old to me, I would make sure you ran git pull --rebase, then check "which jetp".  Maybe if you installed jetp via crate it is in your path ahead of the version built from source?

commit b4914843ac1fc466454f0323cc25176aaa6420a5
Author: Michael DeHaan <michael@michaeldehaan.net>
Date:   Mon Oct 2 17:53:32 2023 -0400

    add code to apt so it will return when the package doesn't need to be updated

**Comment by bellackn** [comment]
you're right, i was using `jetp` from the wrong path. oops. it works alright on the latest version. thanks!
